version: '2'
services:
  app:
    image: nginx
    volumes:
      - ./content:/usr/share/nginx/html:ro
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./backend-not-found.html:/var/www/html/backend-not-found.html
      - ${HOME}/dev/random/home/certbot/conf/archive/m634.dev/privkey3.pem:/etc/ssl/certs/nginx/server.key
      - ${HOME}/dev/random/home/certbot/conf/archive/m634.dev/fullchain3.pem:/etc/ssl/certs/nginx/server.crt
    ports:
      - "80:80"
      - "443:443"
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw